export const ADD_INGREDIANT = 'ADD_INGREDIANT';
export const REMOVE_INGREDIANT = 'REMOVE_INGREDIANT';
export const SET_INGREDIANT = 'SET_INGREDIANT';
export const FECTHCHED_INGREDIANT_FAILED = 'FECTHCHED_INGREDIANT_FAILED';

export const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
export const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
export const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";

export const PURCHASE_INIT = 'PURCHASE_INIT';


export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS";
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_START = "FETCH_ORDER_START";
